version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: "github-actions"
    rebase-strategy: auto
    schedule:
      interveral: "weekly"
  - package-ecosystem: "pip"
    rebase-strategy: auto
    open-pull-requests-limit: 5
    directory: "/"
    schedule:
      interval: "daily"